# Generated by Django 3.2 on 2023-10-05 18:02

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230728_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/images', validators=[recipes.validators.validate_file_size], verbose_name='Изображение'),
        ),
    ]
